//
//  AgentEvent.swift
//  Shared — AgentDeck
//
//  Agent event model (SPEC §10.2). Every structured event carries §10.4
//  confidence and a versioned payload (`payloadV` per payload type, §9).
//  The iOS UI binds ONLY to these shared models — never to provider JSON.
//  Constitution #2: never fabricate structured events; uncertain parses
//  degrade to `rawOutput` with low confidence, not invented structure.
//

import Foundation

/// A structured agent event on the shared timeline (§10.2, §10.4).
public struct AgentEvent: Sendable, Equatable, Identifiable {
    public let id: EventID
    public let sessionID: SessionID
    public let agent: AgentIdentifier
    /// Per-session monotonic sequence; the basis of `EventCursor` (§9).
    public let sequence: UInt64
    /// Unix ms.
    public let timestamp: Int64
    /// §10.4 adapter confidence.
    public let confidence: EventConfidence
    public let payload: AgentEventPayload

    public init(
        id: EventID = .random(),
        sessionID: SessionID,
        agent: AgentIdentifier,
        sequence: UInt64,
        timestamp: Int64,
        confidence: EventConfidence,
        payload: AgentEventPayload
    ) {
        self.id = id
        self.sessionID = sessionID
        self.agent = agent
        self.sequence = sequence
        self.timestamp = timestamp
        self.confidence = confidence
        self.payload = payload
    }

    /// The resume cursor pointing AT this event (§9, §14.1).
    public var cursor: EventCursor {
        EventCursor(sessionID: sessionID, lastEventSequence: sequence)
    }

    /// §10.4: whether this event may populate approval surfaces.
    public var isApprovalEligible: Bool { confidence.isApprovalEligible }
}

/// Versioned event payloads (§9: every payload type carries `payloadV`).
public enum AgentEventPayload: Sendable, Equatable {
    case stateChanged(SessionStateChange)
    case messageText(MessageText)
    case toolCallStarted(ToolCall)
    case toolCallFinished(ToolCallResult)
    case commandStarted(CommandStart)
    case commandFinished(CommandResult)
    case fileOperation(FileOperation)
    case diffAvailable(DiffSummary)
    case approvalRequested(ApprovalRequest)
    case approvalResolved(ApprovalResolution)
    case waitingForUser(UserQuestion)
    case plan(PlanUpdate)
    case fileSearch(FileSearchResult)
    case build(BuildReport)
    case test(TestReport)
    case warning(AgentWarning)
    case completed(CompletionResult)
    case failed(AgentErrorInfo)
    /// Degraded output for uncertain parses (§10.4) — shown raw, never
    /// dressed up as structure (Constitution #2).
    case rawOutput(RawOutput)
    /// Transport-level notices (event-gap markers, resume pagination) —
    /// generated by the transport itself, never by an agent, and honest
    /// about degradation (Constitution #2).
    case transport(TransportNotice)

    /// Wire discriminator values (stable; renaming a case must not change them).
    public var kind: String {
        switch self {
        case .stateChanged: "stateChanged"
        case .messageText: "messageText"
        case .toolCallStarted: "toolCallStarted"
        case .toolCallFinished: "toolCallFinished"
        case .commandStarted: "commandStarted"
        case .commandFinished: "commandFinished"
        case .fileOperation: "fileOperation"
        case .diffAvailable: "diffAvailable"
        case .approvalRequested: "approvalRequested"
        case .approvalResolved: "approvalResolved"
        case .waitingForUser: "waitingForUser"
        case .plan: "plan"
        case .fileSearch: "fileSearch"
        case .build: "build"
        case .test: "test"
        case .warning: "warning"
        case .completed: "completed"
        case .failed: "failed"
        case .rawOutput: "rawOutput"
        case .transport: "transport"
        }
    }
}

// MARK: - Payload value types (§10.2). Each has payloadV = 1.

public struct SessionStateChange: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let from: SessionActivityState
    public let to: SessionActivityState

    public init(from: SessionActivityState, to: SessionActivityState) {
        self.from = from
        self.to = to
    }
}

public enum MessageRole: String, Sendable, CaseIterable, Codable, JSONValueConvertible {
    case user
    case agent
    case system
}

public struct MessageText: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let role: MessageRole
    public let text: String

    public init(role: MessageRole, text: String) {
        self.role = role
        self.text = text
    }
}

public struct ToolCall: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let id: ToolCallID
    public let name: String
    public let summary: String

    public init(id: ToolCallID, name: String, summary: String) {
        self.id = id
        self.name = name
        self.summary = summary
    }
}

public struct ToolCallResult: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let id: ToolCallID
    public let succeeded: Bool
    public let summary: String

    public init(id: ToolCallID, succeeded: Bool, summary: String) {
        self.id = id
        self.succeeded = succeeded
        self.summary = summary
    }
}

public struct CommandStart: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let id: ToolCallID
    public let command: String
    public let workingDirectory: String

    public init(id: ToolCallID, command: String, workingDirectory: String) {
        self.id = id
        self.command = command
        self.workingDirectory = workingDirectory
    }
}

public struct CommandResult: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let id: ToolCallID
    /// nil when the process was killed / never produced an exit status.
    public let exitCode: Int64?
    public let durationMilliseconds: Int64
    public let outputSummary: String

    public init(id: ToolCallID, exitCode: Int64?, durationMilliseconds: Int64, outputSummary: String) {
        self.id = id
        self.exitCode = exitCode
        self.durationMilliseconds = durationMilliseconds
        self.outputSummary = outputSummary
    }
}

public enum FileOperationKind: String, Sendable, CaseIterable, Codable, JSONValueConvertible {
    case read
    case create
    case modify
    case delete
    case rename
}

public struct FileOperation: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let kind: FileOperationKind
    public let path: String

    public init(kind: FileOperationKind, path: String) {
        self.kind = kind
        self.path = path
    }
}

public struct DiffSummary: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let filesChanged: Int64
    public let additions: Int64
    public let deletions: Int64

    public init(filesChanged: Int64, additions: Int64, deletions: Int64) {
        self.filesChanged = filesChanged
        self.additions = additions
        self.deletions = deletions
    }
}

public struct UserQuestion: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let question: String

    public init(question: String) {
        self.question = question
    }
}

public struct CompletionResult: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let succeeded: Bool
    public let summary: String

    public init(succeeded: Bool, summary: String) {
        self.succeeded = succeeded
        self.summary = summary
    }
}

/// §10.2 recovery action advertised alongside an error.
public enum RecoveryAction: String, Sendable, CaseIterable, Codable, JSONValueConvertible {
    case retry
    case reconnect
    case restartSession
    case reauthenticate
    case none
}

public struct AgentErrorInfo: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let code: String
    public let message: String
    public let recovery: RecoveryAction

    public init(code: String, message: String, recovery: RecoveryAction) {
        self.code = code
        self.message = message
        self.recovery = recovery
    }
}

public struct RawOutput: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let text: String
    /// Why this output is raw (e.g. "parse failed", "below confidence floor").
    public let reason: String

    public init(text: String, reason: String) {
        self.text = text
        self.reason = reason
    }
}

// MARK: - Additive payload kinds (plan/file-search/build/test/warning/transport).
// Added after v1; decode is additive-safe: old data still decodes, and
// unknown kinds surface as typed decoding errors — never crashes, never
// guesses (Constitution #2).

/// §10.2 agent plan snapshot: what the agent intends to do, in order.
public struct PlanUpdate: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let summary: String
    public let steps: [String]

    public init(summary: String, steps: [String]) {
        self.summary = summary
        self.steps = steps
    }
}

/// §10.2 file-search results an agent surfaced while exploring.
public struct FileSearchResult: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let query: String
    public let matches: [String]

    public init(query: String, matches: [String]) {
        self.query = query
        self.matches = matches
    }
}

/// §10.2 build outcome.
public struct BuildReport: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let succeeded: Bool
    public let summary: String

    public init(succeeded: Bool, summary: String) {
        self.succeeded = succeeded
        self.summary = summary
    }
}

/// §10.2 test-run outcome.
public struct TestReport: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let succeeded: Bool
    public let passedCount: Int64
    public let failedCount: Int64
    public let summary: String

    public init(succeeded: Bool, passedCount: Int64, failedCount: Int64, summary: String) {
        self.succeeded = succeeded
        self.passedCount = passedCount
        self.failedCount = failedCount
        self.summary = summary
    }
}

/// §10.2 non-fatal warning surfaced by the agent or the transport.
public struct AgentWarning: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let message: String

    public init(message: String) {
        self.message = message
    }
}

/// Transport-notice codes. Decoding is UNKNOWN-TOLERANT: a notice code a
/// build does not recognize decodes as `.unknown` instead of throwing, so
/// newer transport markers never break older peers (§9 forward compat).
public enum TransportNoticeCode: String, Sendable, CaseIterable, Codable {
    /// Events were dropped from persistence at the per-session cap; the
    /// timeline has an honestly-declared hole.
    case eventGap
    /// End of a resume page; metadata carries hasMore + the next cursor.
    case resumePage
    /// Placeholder for codes this build does not recognize.
    case unknown
}

/// A transport-generated notice (never agent output): gap markers and
/// resume-pagination markers. `metadata` carries notice-specific fields
/// (e.g. `hasMore`, `droppedCount`) so new fields don't need new payloadV.
public struct TransportNotice: Sendable, Equatable {
    public static let payloadV: Int64 = 1
    public let code: TransportNoticeCode
    public let message: String
    public let metadata: JSONValue

    public init(code: TransportNoticeCode, message: String, metadata: JSONValue = .object([:])) {
        self.code = code
        self.message = message
        self.metadata = metadata
    }
}

extension TransportNoticeCode: JSONValueConvertible {
    public init(jsonValue: JSONValue) throws {
        guard let raw = jsonValue.stringValue else {
            throw JSONValueDecodingError.invalidValue(
                field: String(describing: Self.self), reason: "code is not a string"
            )
        }
        // Unknown-tolerant on purpose (see type doc).
        self = TransportNoticeCode(rawValue: raw) ?? .unknown
    }

    public func toJSONValue() -> JSONValue { .string(rawValue) }
}
